### ISSUE TITLE
Build successs, but runtime error

### ISSUE THREAD

**Issue by sudostack** [saitoxu/InstaClone#2]
Excuse my question/issue. This is my first time attempting to run a react-native app, but I'm receiving the following error in the simulator:

![screen shot 2017-11-12 at 4 49 50 pm](https://user-images.githubusercontent.com/861147/32705462-92c5a848-c7c9-11e7-85aa-bdd93723a939.png)

macOS v10.13.1
Xcode v9.1 (9B55)
node v9.1.0
yarn v1.3.2
**dependencies:**
```json
        "dependencies": {
                "react": "16.0.0-alpha.12",
                "react-native": "^0.50.3",
                "react-native-navigation": "^1.1.205",
                "react-native-vector-icons": "^4.3.0",
                "react-native-video": "^2.0.0"
        },
        "devDependencies": {
                "babel-jest": "20.0.3",
                "babel-preset-react-native": "2.1.0",
                "jest": "20.0.4",
                "react-test-renderer": "16.0.0-alpha.12"
```

Let me know if yo have any ideas

**Comment by saitoxu** [comment]
I think the cause is the difference of version of React Native (I used 0.44, but you are using 0.50.3).
I upgraded React Native version, so please pull the latest code and check again.

**Comment by sudostack** [comment]
@saitoxu wow! thanks! I'll test-drive when I get home :)

**Comment by sudostack** [comment]
It worked! It took about 20 minutes to build on my 2012 MacBook Air, but it worked and it looks awesome! Thanks!
