### ISSUE TITLE
Consider adding an (open source) license

### ISSUE THREAD

**Issue by devdudeNL** [saitoxu/InstaClone#3]
Hi there,

Thank you for sharing this. I’m using your project to learn React Native in a practical way.

You should consider adding an open source license like MIT. Without a license this is considered proprietary code and can’t be reused. Someone (e.g. me) would need to rewrite all the code for it to be legal.

Consider it. If you don’t like the idea, let me know as well.

(I edited this message because I misclicked the submit button)

**Comment by saitoxu** [comment]
Thank you for notice me, I added a MIT License.
