### ISSUE TITLE
Unable to run it

### ISSUE THREAD

**Issue by Asfandtnt** [saitoxu/InstaClone#4]
is there any body who is able to run it properly ?
have you tested  it for android ?
following is my first error after build.
![screenshot_20180314-165705 7468](https://user-images.githubusercontent.com/22520527/37401187-15ed4be2-27a9-11e8-86cb-fe8f06d0d596.png)

it went away after following command
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

but then i am facing following erro
![screenshot2](https://user-images.githubusercontent.com/22520527/37401458-ea7fa0e4-27a9-11e8-9997-d3f6c38234ae.png)

**Comment by saitoxu** [comment]
Currently, I don't support Android.
If you want to run this app on Android, you need to follow this instrcution.
https://wix.github.io/react-native-navigation/#/installation-android
